[package]
name = "messagepack_to_json"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.26"
eframe = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1"
base64 = "0.21"
clipboard = "0.5.0"
hex = "0.4"
